/// Centralized list of interests/categories used across the app
/// Used by both Ad Targeting and Video Upload category selection
const List<String> kInterestOptions = [
  // Gaming & Entertainment
  'Gaming',
  'Mobile Games',
  'PC Gaming',
  'Console Gaming',
  'Esports',
  'Game Development',
  'Gaming Streams',
  'Gaming Reviews',
  'Indie Games',
  'Retro Gaming',
  'Gaming Hardware',
  'Gaming Accessories',

  // Educational Content
  'Education',
  'Online Learning',
  'Coding & Programming',
  'Web Development',
  'Mobile App Development',
  'Data Science',
  'Machine Learning',
  'Artificial Intelligence',
  'Cybersecurity',
  'Digital Marketing',
  'Graphic Design',
  'Video Editing',
  'Photography',
  'Music Production',
  'Language Learning',
  'Mathematics',
  'Science',
  'Physics',
  'Chemistry',
  'Biology',
  'History',
  'Geography',
  'Literature',
  'Philosophy',
  'Psychology',
  'Business Studies',
  'Finance & Economics',
  'Tutorials',
  'How-to Guides',
  'Skill Development',
  'Career Development',

  // Technology & Innovation
  'Technology',
  'Software Development',
  'Tech Reviews',
  'Gadgets',
  'Smartphones',
  'Laptops',
  'Tablets',
  'Wearables',
  'IoT Devices',
  'Tech News',
  'Innovation',
  'Startups',
  'Entrepreneurship',

  // Creative & Arts
  'Art & Design',
  'Digital Art',
  'UI/UX Design',
  'Animation',
  '3D Modeling',
  'Creative Writing',
  'Content Creation',
  'YouTube',
  'TikTok',
  'Instagram',
  'Social Media',

  // Health & Wellness
  'Health & Fitness',
  'Mental Health',
  'Yoga',
  'Meditation',
  'Nutrition',
  'Exercise',
  'Wellness',

  // Custom Interest Option (used in ad screen picker)
  'Custom Interest',
];
