# Pre-commit hooks to prevent regression
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: flutter-analyze
        name: Flutter Analyze
        entry: bash -c 'cd "snehayog with frontend" && flutter analyze --fatal-infos'
        language: system
        files: \.dart$
        pass_filenames: false

      - id: flutter-format
        name: Flutter Format
        entry: bash -c 'cd "snehayog with frontend" && dart format --set-exit-if-changed .'
        language: system
        files: \.dart$
        pass_filenames: false

      - id: flutter-test
        name: Flutter Test
        entry: bash -c 'cd "snehayog with frontend" && flutter test'
        language: system
        files: \.dart$
        pass_filenames: false

      - id: check-pubspec
        name: Check pubspec.yaml
        entry: bash -c 'cd "snehayog with frontend" && flutter pub get --dry-run'
        language: system
        files: pubspec\.yaml$
        pass_filenames: false
