# Generated by Flutter – custom rules for release builds.
# Suppress missing javax.xml.stream classes referenced by Apache Tika inside
# the video_thumbnail plugin. The code path is never executed on Android, so
# it's safe to silence the warning instead of bundling an extra dependency.
-dontwarn javax.xml.stream.**

